export const elements = [
  { number: 1, symbol : "H", name: "Hydrogen", group: "nonmetal", col: 1, row: 1, atomicMass: "1.00784 u", discoverer: "Henry Cavendish", year: 1766 },
  { number: 2, symbol: "He", name: "Helium", group: "noble-gas", col: 19, row: 1, atomicMass: "4.00260 u", discoverer: "William Ramsay, Norman Lockyer, Per Teodor Cleve, Pierre Janssen", year: 1894 },
  { number: 3, symbol: "Li", name: "Lithium", group: "alkali-metal", col: 1, row: 2, atomicMass: "6.941 u", discoverer: "Johan August Arfwedson", year: 1817 },
  { number: 4, symbol: "Be", name: "Beryllium", group: "alkaline-earth", col: 2, row: 2, atomicMass: "9.01218 u", discoverer: "Louis Nicolas Vauquelin, Martin Heinrich Klaproth", year: 1798 },
  { number: 5, symbol: "B", name: "Boron", group: "metalloid", col: 14, row: 2, atomicMass: "10.81 u", discoverer: "Humphry Davy, Joseph Louis Gay-Lussac, Louis Jacques Thénard", year: 1808 },
  { number: 6, symbol: "C", name: "Carbon", group: "nonmetal", col: 15, row: 2, atomicMass: "12.011 u", discoverer: "Antoine Lavosier", year: "Unknown" },
  { number: 7, symbol: "N", name: "Nitrogen", group: "nonmetal", col: 16, row: 2, atomicMass: "14.007 u", discoverer: "Daniel Rutherford", year: 1772 },
  { number: 8, symbol: "O", name: "Oxygen", group: "nonmetal", col:  17, row: 2, atomicMass: "15.999 u", discoverer: "Antoine Lavoisier,Joseph Priestley, Carl Wilhelm Scheele", year:  1774 },
  { number: 9, symbol: "F", name: "Fluorine", group:  "halogen", col:  18, row:  2, atomicMass:  "18.998 u", discoverer:  "Henri Moissan", year:  1886 },
  { number: 10, symbol:  "Ne", name:  "Neon", group:  "noble-gas", col:  19, row:  2, atomicMass:  "20.180 u", discoverer:  "William Ramsay, Morris Travers", year: 1890 },
  { number: 11, symbol:  "Na", name:  "Sodium", group:  "alkali-metal", col:  1, row:  3, atomicMass:  "22.989 u", discoverer:  "Humphry Davy", year: 1807 },
  { number: 12, symbol:  "Mg", name:  "Magnesium", group:  "alkaline-earth", col:  2, row:  3, atomicMass:  "24.305 u", discoverer:  "Humphry Davy, Joseph Black", year: 1755 },
  { number: 13, symbol: "Al", name: "Aluminum", group: "post-transition", col: 14, row: 3, atomicMass: "26.982 u", discoverer: "Hans Christian Ørsted", year: 1825 },
  { number: 14, symbol: "Si", name: "Silicon", group: "metalloid", col: 15, row: 3, atomicMass: "28.085 u", discoverer: "Antoine Lavoisier, Jöns Jacob Berzelius", year: 1823 },
  { number: 15, symbol: "P", name: "Phosphorus", group: "nonmetal", col: 16, row: 3, atomicMass: "30.974 u", discoverer: "Hennig Brand", year: 1669 },
  { number: 16, symbol: "S", name: "Sulfur", group: "nonmetal", col: 17, row: 3, atomicMass: "32.06 u", discoverer: "Ancient Egypt and Greece", year: "Unknown" },
  { number: 17, symbol: "Cl", name: "Chlorine", group: "halogen", col: 18, row: 3, atomicMass: "35.45 u", discoverer: "Carl Wilhelm Scheele", year: 1774 },
  { number: 18, symbol: "Ar", name: "Argon", group: "noble-gas", col: 19, row: 3, atomicMass: "39.948 u", discoverer: "John William Strutt, 3rd Baron Rayleigh, William Ramsay", year: 1894 },
  { number: 19, symbol: "K", name: "Potassium", group: "alkali-metal", col: 1, row: 4, atomicMass: "39.098 u", discoverer: "Humphry Davy", year: 1807 },
  { number: 20, symbol: "Ca", name: "Calcium", group: "alkaline-earth", col: 2, row: 4, atomicMass: "40.078 u", discoverer: "Humphry Davy", year: 1808 },
  { number: 21, symbol: "Sc", name: "Scandium", group: "transition-metal", col: 3, row: 4, atomicMass: "44.956 u", discoverer: "Per Teodor Cleve, Lars Fredrik Nilson", year: 1879 },
  { number: 22, symbol: "Ti", name: "Titanium", group: "transition-metal", col: 5, row: 4, atomicMass: "47.867 u", discoverer: "Martin Heinrich Klaproth, William Gregor", year: 1791 },
  { number: 23, symbol: "V", name: "Vanadium", group: "transition-metal", col: 6, row: 4, atomicMass: "50.942 u", discoverer: "Andrés Manuel del Río", year: 1801 },
  { number: 24, symbol: "Cr", name: "Chromium", group: "transition-metal", col: 7, row: 4, atomicMass: "51.996 u", discoverer: "Louis Nicolas Vauquelin, Martin Heinrich Klaproth", year: 1797 },
  { number: 25, symbol: "Mn", name: "Manganese", group: "transition-metal", col: 8, row: 4, atomicMass: "54.938 u", discoverer: "Carl Wilhelm Scheele, Johan Gottlieb Gahn, Ignatius Gottfried Kaim", year: 1774 },
  { number: 26, symbol: "Fe", name: "Iron", group: "transition-metal", col: 9, row:  4, atomicMass:  "55.845 u", discoverer:  "Ancient China and Egypt", year:  "Unknown" },
  { number: 27, symbol: "Co", name: "Cobalt", group: "transition-metal", col: 10, row: 4, atomicMass: "58.933 u", discoverer: "Georg Brandt", year: 1735 },
  { number: 28, symbol: "Ni", name: "Nickel", group: "transition-metal", col: 11, row: 4, atomicMass: "58.693 u", discoverer: "Axel Fredrik Cronstedt", year: 1751 },
  { number: 29, symbol: "Cu", name: "Copper", group: "transition-metal", col: 12, row: 4, atomicMass: "63.546 u", discoverer: "Ancient Egypt and Greece", year: "8991 BCE" },
  { number: 30, symbol: "Zn", name: "Zinc", group: "transition-metal", col: 13, row: 4, atomicMass: "65.38 u", discoverer: "Andreas Sigismund Marggraf", year: 1746 },
  { number: 31, symbol: "Ga", name: "Gallium", group: "post-transition", col: 14, row: 4, atomicMass: "69.723 u", discoverer: "Paul Émile Lecoq de Boisbaudran", year: 1875 },
  { number: 32, symbol:  "Ge", name:  "Germanium", group:  "metalloid", col:  15, row:  4, atomicMass:  "72.630 u", discoverer:  "Clemens Winkler", year:  1886 },
  { number: 33, symbol: "As", name: "Arsenic", group: "metalloid", col: 16, row: 4, atomicMass: "74.922 u", discoverer: "Albertus Magnus", year: 1250 },
  { number: 34, symbol: "Se", name: "Selenium", group: "nonmetal", col: 17, row: 4, atomicMass: "78.971 u", discoverer: "Jöns Jacob Berzelius, Johan Gottlieb Gahn", year: 1817 },
  { number: 35, symbol: "Br", name: "Bromine", group: "halogen", col: 18, row: 4, atomicMass: "79.904 u", discoverer: "Antoine Lavoisier, Antoine Jérôme Balard, Carl Jacob Löwig", year: 1826 },
  { number: 36, symbol: "Kr", name: "Krypton", group: "noble-gas", col: 19, row: 4, atomicMass: "83.798 u", discoverer: "William Ramsay, Morris Travers", year: 1898 },
  { number: 37, symbol: "Rb", name: "Rubidium", group: "alkali-metal", col: 1, row: 5, atomicMass: "85.468 u", discoverer: "Robert Bunsen, Gustav Kirchhoff", year: 1861 },
  { number: 38, symbol: "Sr", name: "Strontium", group:  "alkaline-earth", col:  2, row:  5, atomicMass:  "87.62 u", discoverer:  "Humphry Davy, Adair Crawford, William Cruickshank", year:  1790 },
  { number: 39, symbol: "Y", name:  "Yttrium", group:  "transition-metal", col:  3, row:  5, atomicMass:  "88.905 u", discoverer:  "Johan Gadolin", year:  1794 },
  { number: 40, symbol: "Zr", name:  "Zirconium", group:  "transition-metal", col:  5, row:  5, atomicMass:  "91.224 u", discoverer:  "Martin Heinrich Klaproth", year:  1789 },
  { number: 41, symbol: "Nb", name:  "Niobium", group:  "transition-metal", col:  6, row:  5, atomicMass:  "92.906 u", discoverer:  "Charles Hatchett", year:  1801 },
  { number: 42, symbol: "Mo", name:  "Molybdenum", group:  "transition-metal", col:  7, row:  5, atomicMass:  "95.95 u", discoverer:  "Carl Wilhelm Scheele", year:  1778 },
  { number: 43, symbol: "Tc", name: "Technetium", group: "transition-metal", col: 8, row: 5, atomicMass: "98 u", discoverer: "Emilio Segrè, Carlo Perrier", year: 1937 },
  { number: 44, symbol: "Ru", name: "Ruthenium", group: "transition-metal", col: 9, row: 5,  atomicMass: "101.07 u", discoverer: "Karl Ernst Claus", year: 1844 },
  { number: 45, symbol: "Rh", name: "Rhodium", group: "transition-metal", col: 10, row: 5, atomicMass: "102.905 u", discoverer: "William Hyde Wollaston", year: 1803 },
  { number: 46, symbol: "Pd", name: "Palladium", group: "transition-metal", col: 11, row: 5, atomicMass: "106.42 u", discoverer: "William Hyde Wollaston", year: 1803 },
  { number: 47, symbol: "Ag", name: "Silver", group: "transition-metal", col: 12, row: 5, atomicMass: "107.868 u", discoverer: "Unknown", year: "Ancient" },
  { number: 48, symbol: "Cd", name: "Cadmium", group: "transition-metal", col: 13, row: 5, atomicMass: "112.414 u", discoverer: "Friedrich Stromeyer, Karl Samuel Leberecht Hermann", year: 1817 },
  { number: 49, symbol: "In", name: "Indium", group: "post-transition", col: 14, row: 5, atomicMass: "114.818 u", discoverer: "Friedrich Wilhelm Herschel, Ferdinand Reich", year: 1863 },
  { number: 50, symbol: "Sn", name: "Tin", group: "post-transition", col: 15, row: 5, atomicMass: "118.710 u", discoverer: "Unknown", year: "Ancient" },
  { number: 51, symbol: "Sb", name: "Antimony", group: "metalloid", col: 16, row: 5, atomicMass: "121.76 u", discoverer: "Unknown", year: "1599 BCE" },
  { number: 52, symbol: "Te", name: "Tellurium", group: "metalloid", col: 17, row: 5, atomicMass: "127.60 u", discoverer: "Johann Gottlob Lehmann, Martin Heinrich Klaproth, Franz-Joseph Müller von Reichenstein", year: 1782 },
  { number: 53, symbol: "I", name: "Iodine", group: "halogen", col: 18, row: 5, atomicMass: "126.904 u", discoverer: "Bernard Courtois", year: 1811 },
  { number: 54, symbol: "Xe", name: "Xenon", group: "noble-gas", col: 19, row: 5, atomicMass: "131.293 u", discoverer: "William Ramsay, Morris Travers", year: 1898 },
  { number: 55, symbol: "Cs", name: "Cesium", group: "alkali-metal", col: 1, row: 6, atomicMass: "132.905 u", discoverer: "Robert Bunsen, Gustav Kirchhoff", year: 1860 },
  { number: 56, symbol: "Ba", name: "Barium", group: "alkaline-earth", col: 2, row: 6, atomicMass: "137.327 u", discoverer: "Carl Wilhelm Scheele, Humphry Davy", year: 1808 },
  { number: 57, symbol: "La", name: "Lanthanum", group: "lanthanide", col: 3, row: 6, atomicMass: "138.905 u", discoverer: "Carl Gustaf Mosander", year: 1839 },
  { number: 58, symbol: "Ce", name: "Cerium", group: "lanthanide", col: 5, row: 9, atomicMass: "140.116 u", discoverer: "Jöns Jacob Berzelius, Wilhelm Hisinger, Martin Heinrich Klaproth", year: 1803 },
  { number: 59, symbol: "Pr", name: "Praseodymium", group: "lanthanide", col: 6, row: 9, atomicMass: "140.907 u", discoverer: "Carl Auer von Welsbach", year: 1885 },
  { number: 60, symbol: "Nd", name: "Neodymium", group: "lanthanide", col: 7, row: 9, atomicMass: "144.242 u", discoverer: "Carl Auer von Welsbach", year: 1885 },
  { number: 61, symbol: "Pm", name: "Promethium", group: "lanthanide", col: 8, row: 9, atomicMass: "145 u", discoverer: "Jacob A. Marinsky, Lawrence E. Glendenin, Charles D. Coryell", year: 1945 },
  { number: 62, symbol: "Sm", name: "Samarium", group: "lanthanide", col: 9, row: 9, atomicMass: "150.36 u", discoverer: "Paul Émile Lecoq de Boisbaudran", year: 1879 },
  { number: 63, symbol: "Eu", name: "Europium", group: "lanthanide", col: 10, row: 9, atomicMass: "151.964 u", discoverer: "Paul-Émile Lecoq de Boisbaudran, Eugène-André Demarçay", year: 1901 },
  { number: 64, symbol: "Gd", name: "Gadolinium", group: "lanthanide", col: 11, row: 9, atomicMass: "157.25 u", discoverer: "Paul-Émile Lecoq de Boisbaudran, Jean Charles Galissard de Marignac", year: 1880 },
  { number: 65, symbol: "Tb", name: "Terbium", group: "lanthanide", col: 12, row: 9, atomicMass: "158.925 u", discoverer: "Carl Gustaf Mosander", year: 1843 },
  { number: 66, symbol: "Dy", name: "Dysprosium", group: "lanthanide", col: 13, row: 9, atomicMass: "162.500 u", discoverer: "Paul-Émile Lecoq de Boisbaudran", year: 1886 },
  { number: 67, symbol: "Ho", name: "Holmium", group: "lanthanide", col: 14, row: 9, atomicMass: "164.930 u", discoverer: "Per Teodor Cleve, Marc Delafontaine, Jacques-Louis Soret", year: 1878 },
  { number: 68, symbol: "Er", name: "Erbium", group: "lanthanide", col: 15, row: 9, atomicMass: "167.259 u", discoverer: "Carl Gustaf Mosander", year: 1843 },
  { number: 69, symbol: "Tm", name: "Thulium", group: "lanthanide", col: 16, row: 9, atomicMass: "168.934 u", discoverer: "Per Theodor Cleve", year: 1879 },
  { number: 70, symbol: "Yb", name: "Ytterbium", group: "lanthanide", col: 17, row: 9, atomicMass: "173.045 u", discoverer: "Jean Charles Galissard de Marignac", year: 1878 },
  { number: 71, symbol: "Lu", name: "Lutetium", group: "lanthanide", col: 18, row: 9, atomicMass: "174.966 u", discoverer: "Georges Urbain, Carl Auer von Welsbach, Charles James", year: 1907 },
  { number: 72, symbol: "Hf", name: "Hafnium", group: "transition-metal", col: 5, row: 6, atomicMass: "178.49 u", discoverer: "Dmitri Mendeleev, George de Hevesy, Dirk Coster", year: 1923 },
  { number: 73, symbol: "Ta", name: "Tantalum", group: "transition-metal", col: 6, row: 6, atomicMass: "180.947 u", discoverer: "Anders Ekeberg", year: 1802 },
  { number: 74, symbol: "W", name: "Tungsten", group: "transition-metal", col: 7, row: 6, atomicMass: "183.84 u", discoverer: "Juan José Elhuyar, Fausto Elhuyar, Carl Wilhelm Scheele", year: 1783 },
  { number: 75, symbol: "Re", name: "Rhenium", group: "transition-metal", col: 8, row: 6, atomicMass: "186.207 u", discoverer: "Masataka Fujita, Walter Noddack, Ida Noddack", year: 1925 },
  { number: 76, symbol: "Os", name: "Osmium", group: "transition-metal", col: 9, row: 6, atomicMass: "190.23 u", discoverer: "Smithson Tennant", year: 1803 },
  { number: 77, symbol: "Ir", name: "Iridium", group: "transition-metal", col: 10, row: 6, atomicMass: "192.217 u", discoverer: "Smithson Tennant", year: 1803 },
  { number: 78, symbol: "Pt", name: "Platinum", group: "transition-metal", col: 11, row: 6, atomicMass: "195.084 u", discoverer: "Antonio de Ulloa", year: 1735 },
  { number: 79, symbol: "Au", name: "Gold", group: "transition-metal", col: 12, row: 6, atomicMass: "196.966 u", discoverer: "Unknown", year: "Ancient" },
  { number: 80, symbol: "Hg", name: "Mercury", group: "transition-metal", col: 13, row: 6, atomicMass: "200.592 u", discoverer: "Unknown", year: "Ancient" },
  { number: 81, symbol: "Tl", name: "Thallium", group: "post-transition", col: 14, row: 6, atomicMass: "204.383 u", discoverer: "William Crookes", year: 1861 },
  { number: 82, symbol: "Pb", name: "Lead", group: "post-transition", col: 15, row: 6, atomicMass: "207.2 u", discoverer: "Unknown", year: "Ancient" },
  { number: 83, symbol: "Bi", name: "Bismuth", group: "post-transition", col: 16, row: 6, atomicMass: "208.980 u", discoverer: "Claude François Geoffroy", year: 1753 },
  { number: 84, symbol: "Po", name: "Polonium", group: "post-transition", col: 17, row: 6, atomicMass: "209 u", discoverer: "Pierre Curie, Marie Curie", year: 1898 },
  { number: 85, symbol: "At", name: "Astatine", group: "halogen", col: 18, row: 6, atomicMass: "210 u", discoverer: "Dale R. Corson, Kenneth Ross MacKenzie, H. Wayne Mierck, Emilio Segrè", year: 1940 },
  { number: 86, symbol: "Rn", name: "Radon", group: "noble-gas", col: 19, row: 6, atomicMass: "222 u", discoverer: "Friedrich Ernst Dorn", year: 1900 },
  { number: 87, symbol: "Fr", name: "Francium", group: "alkali-metal", col: 1, row: 7, atomicMass: "223 u", discoverer: "Marguerite Perey", year: 1939 },
  { number: 88, symbol: "Ra", name: "Radium", group: "alkaline-earth", col: 2, row: 7, atomicMass: "226 u", discoverer: "Pierre Curie, Marie Curie", year: 1898 },
  { number: 89, symbol: "Ac", name: "Actinium", group: "actinide", col: 3, row: 7, atomicMass: "227 u", discoverer: "André-Louis Debierne", year: 1899 },
  { number: 90, symbol: "Th", name: "Thorium", group: "actinide", col: 5, row: 10, atomicMass: "232.038 u", discoverer: "Jöns Jacob Berzelius", year: 1828 },
  { number: 91, symbol: "Pa", name: "Protactinium", group: "actinide", col: 6, row: 10, atomicMass: "231.035 u", discoverer: "Friedrich Oskar Giesel", year: 1913 },
  { number: 92, symbol: "U", name: "Uranium", group: "actinide", col: 7, row: 10, atomicMass: "238.028 u", discoverer: "Martin Heinrich Klaproth", year: 1789 },
  { number: 93, symbol: "Np", name: "Neptunium", group: "actinide", col: 8, row: 10, atomicMass: "237 u", discoverer: "Edwin McMillan, Philip H. Abelson", year: 1940 },
  { number: 94, symbol: "Pu", name: "Plutonium", group: "actinide", col: 9, row: 10, atomicMass: "244 u", discoverer: "Glenn T. Seaborg, Edwin McMillan, Joseph W. Kennedy, Arthur C. Wahl", year: 1940 },
  { number: 95, symbol: "Am", name: "Americium", group: "actinide", col: 10, row: 10, atomicMass: "243 u", discoverer: "Glenn T. Seaborg, Ralph A. James, Leon O. Morgan", year: 1944 },
  { number: 96, symbol: "Cm", name: "Curium", group: "actinide", col: 11, row: 10, atomicMass: "247 u", discoverer: "Glenn T. Seaborg, Ralph A. James, Leon O. Morgan", year: 1944 },
  { number: 97, symbol: "Bk", name: "Berkelium", group: "actinide", col: 12, row: 10, atomicMass: "247 u", discoverer: "Glenn T. Seaborg, Albert Ghiorso", year: 1949 },
  { number: 98, symbol: "Cf", name: "Californium", group: "actinide", col: 13, row: 10, atomicMass: "251 u", discoverer: "Glenn T. Seaborg, Albert Ghiorso", year: 1950 },
  { number: 99, symbol: "Es", name: "Einsteinium", group: "actinide", col: 14, row: 10, atomicMass: "252 u", discoverer: "Albert Ghiorso, Glenn T. Seaborg, Bernard G. Harvey, Gregory R. Choppin", year: 1952 },
  { number: 100, symbol: "Fm", name: "Fermium", group: "actinide", col: 15, row: 10, atomicMass: "257 u", discoverer: "Albert Ghiorso, Glenn T. Seaborg, Bernard G. Harvey, Gregory R. Choppin", year: 1953 },
  { number: 101, symbol: "Md", name: "Mendelevium", group: "actinide", col: 16, row: 10, atomicMass: "258 u", discoverer: "Albert Ghiorso, Glenn T. Seaborg, Bernard G. Harvey, Gregory R. Choppin", year: 1955 },
  { number: 102, symbol: "No", name: "Nobelium", group: "actinide", col: 17, row: 10, atomicMass: "259 u", discoverer: "Albert Ghiorso, Glenn T. Seaborg, Bernard G. Harvey, Gregory R. Choppin", year: 1958 },
  { number: 103, symbol: "Lr", name: "Lawrencium", group: "actinide", col: 18, row: 10, atomicMass: "262 u", discoverer: "Albert Ghiorso, Glenn T. Seaborg, Bernard G. Harvey, Gregory R. Choppin", year: 1961 },
  { number: 104, symbol: "Rf", name: "Rutherfordium", group: "transition-metal", col: 5, row: 7, atomicMass: "267 u", discoverer: "Albert Ghiorso, Glenn T. Seaborg, Bernard G. Harvey, Gregory R. Choppin", year: 1964 },
  { number: 105, symbol: "Db", name: "Dubnium", group: "transition-metal", col: 6, row: 7, atomicMass: "270 u", discoverer: "Albert Ghiorso, Glenn T. Seaborg, Bernard G. Harvey, Gregory R. Choppin", year: 1967 },
  { number: 106, symbol: "Sg", name: "Seaborgium", group: "transition-metal", col: 7, row: 7, atomicMass: "271 u", discoverer: "Albert Ghiorso, Glenn T. Seaborg, Bernard G. Harvey, Gregory R. Choppin", year: 1974 },
  { number: 107, symbol: "Bh", name: "Bohrium", group: "transition-metal", col: 8, row: 7, atomicMass: "270 u", discoverer: "Albert Ghiorso, Glenn T. Seaborg, Bernard G. Harvey, Gregory R. Choppin", year: 1981 },
  { number: 108, symbol: "Hs", name: "Hassium", group: "transition-metal", col: 9, row: 7, atomicMass: "270 u", discoverer: "Albert Ghiorso, Glenn T. Seaborg, Bernard G. Harvey, Gregory R. Choppin", year: 1984 },
  { number: 109, symbol: "Mt", name: "Meitnerium", group: "transition-metal", col: 10, row: 7, atomicMass: "276 u", discoverer: "Albert Ghiorso, Glenn T. Seaborg, Bernard G. Harvey, Gregory R. Choppin", year: 1982 },
  { number: 110, symbol: "Ds", name: "Darmstadtium", group: "transition-metal", col: 11, row: 7, atomicMass: "281 u", discoverer: "Sigurd Hofmann", year: 1994 },
  { number: 111, symbol: "Rg", name: "Roentgenium", group: "transition-metal", col: 12, row:  7, atomicMass:  "282 u", discoverer:  "Victor Ninov, Sigurd Hofmann", year:  1994 },
  { number: 112, symbol: "Cn", name: "Copernicium", group: "transition-metal", col: 13, row: 7, atomicMass: "285 u", discoverer: "Sigurd Hofmann, Victor Ninov", year: 1996 },
  { number: 113, symbol: "Nh", name: "Nihonium", group: "post-transition", col: 14, row: 7, atomicMass: "286 u", discoverer: "Sigurd Hofmann, Victor Ninov", year: 2003 },
  { number: 114, symbol: "Fl", name: "Flerovium", group: "post-transition", col: 15, row: 7, atomicMass: "289 u", discoverer: "Yuri Oganessian, Sigurd Hofmann, Flerov Laboratory of Nuclear Reactions", year: 1998 },
  { number: 115, symbol: "Mc", name: "Moscovium", group: "post-transition", col: 16, row: 7, atomicMass: "290 u", discoverer: "Joint Institute for Nuclear Research", year: 2003 },
  { number: 116, symbol: "Lv", name: "Livermorium", group: "post-transition", col: 17, row: 7, atomicMass: "293 u", discoverer: "Joint Institute for Nuclear Research, Yuri Oganessian", year: 2000 },
  { number: 117, symbol: "Ts", name: "Tennessine", group: "halogen", col: 18, row: 7, atomicMass: "294 u", discoverer: "Joint Institute for Nuclear Research, Yuri Oganessian", year: 2010 },
  { number: 118, symbol: "Og", name: "Oganesson", group: "noble-gas", col: 19, row: 7, atomicMass: "294 u", discoverer: "Joint Institute for Nuclear Research, Yuri Oganessian", year: 2006 }
];